-- =====================================================
-- ベースラインマイグレーション: 基本テーブル作成
--
-- 初期セットアップ時にSupabaseダッシュボードで手動作成された
-- テーブルを再現する。
--
-- 既存プロジェクト（survey-app / survey-app-dev）には
-- supabase migration repair --status applied で履歴登録のみ。
-- 新規プロジェクトでは supabase db push の起点として実行される。
--
-- ※ client_code カラム、RLS、複合PKは後続マイグレーションで追加:
--   20260424000001: client_code カラム + clients テーブル + RLS
--   20260424000003: departments / qq_conditions を複合PKに変更
-- =====================================================

-- clients テーブル
-- （20260424000001 でも CREATE TABLE IF NOT EXISTS で作成されるため競合しない）
CREATE TABLE IF NOT EXISTS clients (
  code text PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- departments（client_code 追加前の初期状態・単一PK）
CREATE TABLE IF NOT EXISTS departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);

-- qq_conditions（client_code 追加前の初期状態・単一PK）
CREATE TABLE IF NOT EXISTS qq_conditions (
  id text NOT NULL PRIMARY KEY,
  label text NOT NULL,
  pain_areas text[] NOT NULL DEFAULT '{}',
  sort_order integer NOT NULL DEFAULT 0
);

-- survey_responses（client_code 追加前の初期状態）
CREATE TABLE IF NOT EXISTS survey_responses (
  id text NOT NULL PRIMARY KEY,
  submitted_at timestamptz NOT NULL,
  department text NOT NULL,
  age_group text NOT NULL,
  gender text NOT NULL,
  qq_condition text NOT NULL,
  symptom_days_past30 integer NOT NULL,
  work_quantity integer NOT NULL,
  work_quality integer NOT NULL,
  had_absenteeism boolean NOT NULL,
  monthly_salary_man_yen integer NOT NULL,
  we_vigor integer NOT NULL,
  we_dedication integer NOT NULL,
  we_absorption integer NOT NULL
);