-- =====================================================
-- 設問設計書 v1.1 対応: DBスキーマ再設計
--
-- 変更内容:
--   1. clients: モジュールON/OFF・少人数閾値カラム追加
--   2. survey_rounds: 新規作成（実施回エンティティ）
--   3. survey_responses: 廃止カラム削除・新カラム追加
--   4. qq_conditions: 17選択肢 → 16選択肢に更新
--   5. 第2部テーブル新規作成（4テーブル）
--   6. RLSポリシー追加
--
-- 参考: docs/設計/260810 DBスキーマ設計書.md
-- =====================================================

-- =====================================================
-- Step 1: clients テーブルへのカラム追加
-- =====================================================
ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS min_display_count      integer NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS module_mental_health   boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS module_company_support boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS module_work_life       boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS module_exercise        boolean NOT NULL DEFAULT false;

-- =====================================================
-- Step 2: survey_rounds テーブルの新規作成
-- =====================================================
CREATE TABLE IF NOT EXISTS survey_rounds (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_code text        NOT NULL REFERENCES clients(code),
  title       text        NOT NULL,
  started_at  timestamptz,
  ended_at    timestamptz,
  created_at  timestamptz DEFAULT now()
);

ALTER TABLE survey_rounds ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "survey_rounds_admin"        ON survey_rounds;
DROP POLICY IF EXISTS "survey_rounds_client_admin" ON survey_rounds;
DROP POLICY IF EXISTS "survey_rounds_anon"         ON survey_rounds;

CREATE POLICY "survey_rounds_admin" ON survey_rounds FOR ALL
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'system_admin');

CREATE POLICY "survey_rounds_client_admin" ON survey_rounds FOR SELECT
  USING (
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'client_admin'
    AND client_code = (auth.jwt() -> 'app_metadata' ->> 'client_code')
  );

-- anon はアンケートURL上の実施回を参照するために SELECT のみ許可
CREATE POLICY "survey_rounds_anon" ON survey_rounds FOR SELECT
  USING (auth.role() = 'anon');

-- =====================================================
-- Step 3: survey_responses の再設計
--
-- 開発環境のため既存データをすべて削除してからスキーマ変更する。
-- =====================================================

-- 既存データを削除
TRUNCATE TABLE survey_responses;

-- 廃止カラムを削除
ALTER TABLE survey_responses
  DROP COLUMN IF EXISTS age_group,
  DROP COLUMN IF EXISTS qq_condition,
  DROP COLUMN IF EXISTS had_absenteeism,
  DROP COLUMN IF EXISTS monthly_salary_man_yen,
  DROP COLUMN IF EXISTS we_vigor,
  DROP COLUMN IF EXISTS we_dedication,
  DROP COLUMN IF EXISTS we_absorption;

-- 新カラムを追加
ALTER TABLE survey_responses
  ADD COLUMN survey_round_id          bigint  NOT NULL REFERENCES survey_rounds(id),
  ADD COLUMN full_name                text    NOT NULL,
  ADD COLUMN date_of_birth            date    NOT NULL,
  ADD COLUMN employment_type          text    NOT NULL,
  ADD COLUMN symptom_conditions       text[]  NOT NULL DEFAULT '{}',
  ADD COLUMN symptom_conditions_other text,
  ADD COLUMN primary_condition        text,
  ADD COLUMN absentee_days_past_year  integer NOT NULL DEFAULT 0,
  ADD COLUMN treatment_places         text[]  NOT NULL DEFAULT '{}',
  ADD COLUMN treatment_places_other   text,
  ADD COLUMN treatment_frequency      integer,
  ADD COLUMN daily_items              text[]  NOT NULL DEFAULT '{}',
  ADD COLUMN daily_items_other        text,
  ADD COLUMN consultation_health      text    NOT NULL,
  ADD COLUMN consultation_work        text    NOT NULL,
  ADD COLUMN consultation_family      text    NOT NULL,
  ADD COLUMN consultation_mental      text    NOT NULL,
  ADD COLUMN expert_support_intent    text    NOT NULL;

-- =====================================================
-- Step 4: qq_conditions のデータ更新（17 → 16選択肢）
-- =====================================================

-- 廃止: mens_pain / mens_other → womens_health に統合
DELETE FROM qq_conditions WHERE id IN ('mens_pain', 'mens_other');

-- 新規: womens_health を既存の全クライアント分追加
INSERT INTO qq_conditions (id, label, pain_areas, sort_order, client_code)
SELECT
  'womens_health',
  '女性特有の健康課題（月経に伴う不調・更年期の不調など）',
  '{lower_back,head}',
  14,
  client_code
FROM (SELECT DISTINCT client_code FROM qq_conditions) AS existing_clients
ON CONFLICT DO NOTHING;

-- other の sort_order を繰り上げ（旧16 → 新15）
UPDATE qq_conditions SET sort_order = 15 WHERE id = 'other';

-- ラベルを設問設計書 v1.1 に合わせて更新
UPDATE qq_conditions SET label = '不調はない'
  WHERE id = 'none';
UPDATE qq_conditions SET label = 'アレルギーによる不調（花粉症など）'
  WHERE id = 'allergy';
UPDATE qq_conditions SET label = '皮膚の不調（湿疹・かゆみなど）'
  WHERE id = 'skin';
UPDATE qq_conditions SET label = '感染症による不調（風邪・胃腸炎など）'
  WHERE id = 'infection';
UPDATE qq_conditions SET label = '胃腸の不調（下痢・便秘・胃の不快感など）'
  WHERE id = 'gi';
UPDATE qq_conditions SET label = '手足の関節の痛み'
  WHERE id = 'limb_joint';
UPDATE qq_conditions SET label = '首の不調・肩こり'
  WHERE id = 'neck_shoulder';
UPDATE qq_conditions SET label = '頭痛'
  WHERE id = 'headache';
UPDATE qq_conditions SET label = '歯の不調'
  WHERE id = 'dental';
UPDATE qq_conditions SET label = '心の不調（気分の落ち込み・不安など）'
  WHERE id = 'mental';
UPDATE qq_conditions SET label = '睡眠の不調（眠れないなど）'
  WHERE id = 'sleep';
UPDATE qq_conditions SET label = '全身のだるさ・疲れ'
  WHERE id = 'fatigue';
UPDATE qq_conditions SET label = '目の不調（視力低下・疲れ目など）'
  WHERE id = 'eye';
UPDATE qq_conditions SET label = 'その他の不調'
  WHERE id = 'other';

-- =====================================================
-- Step 5: 第2部テーブルの新規作成
-- =====================================================

-- 心の健康モジュール（問17、6項目）
CREATE TABLE IF NOT EXISTS mental_health_responses (
  id                 bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_response_id text        NOT NULL REFERENCES survey_responses(id),
  q17_score          integer     NOT NULL CHECK (q17_score BETWEEN 0 AND 4),
  q18_score          integer     NOT NULL CHECK (q18_score BETWEEN 0 AND 4),
  q19_score          integer     NOT NULL CHECK (q19_score BETWEEN 0 AND 4),
  q20_score          integer     NOT NULL CHECK (q20_score BETWEEN 0 AND 4),
  q21_score          integer     NOT NULL CHECK (q21_score BETWEEN 0 AND 4),
  q22_score          integer     NOT NULL CHECK (q22_score BETWEEN 0 AND 4),
  created_at         timestamptz DEFAULT now()
);

-- 会社のサポートモジュール（問18、4項目）
CREATE TABLE IF NOT EXISTS company_support_responses (
  id                 bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_response_id text        NOT NULL REFERENCES survey_responses(id),
  q23_score          integer     NOT NULL CHECK (q23_score BETWEEN 1 AND 7),
  q24_score          integer     NOT NULL CHECK (q24_score BETWEEN 1 AND 7),
  q25_score          integer     NOT NULL CHECK (q25_score BETWEEN 1 AND 7),
  q26_score          integer     NOT NULL CHECK (q26_score BETWEEN 1 AND 7),
  created_at         timestamptz DEFAULT now()
);

-- 仕事以外の負担モジュール（問19〜20）
CREATE TABLE IF NOT EXISTS work_life_responses (
  id                 bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_response_id text        NOT NULL REFERENCES survey_responses(id),
  role_impact        text        NOT NULL,
  support_desire     text,
  created_at         timestamptz DEFAULT now()
);

-- 運動習慣モジュール（問21〜22）
CREATE TABLE IF NOT EXISTS exercise_responses (
  id                 bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_response_id text        NOT NULL REFERENCES survey_responses(id),
  has_exercise_habit boolean     NOT NULL,
  exercise_days      integer     CHECK (exercise_days BETWEEN 1 AND 7),
  created_at         timestamptz DEFAULT now()
);

-- =====================================================
-- Step 6: 第2部テーブルの RLS
-- =====================================================

ALTER TABLE mental_health_responses   ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_support_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_life_responses       ENABLE ROW LEVEL SECURITY;
ALTER TABLE exercise_responses        ENABLE ROW LEVEL SECURITY;

-- mental_health_responses
DROP POLICY IF EXISTS "mental_health_admin"        ON mental_health_responses;
DROP POLICY IF EXISTS "mental_health_client_admin" ON mental_health_responses;
DROP POLICY IF EXISTS "mental_health_anon_insert"  ON mental_health_responses;

CREATE POLICY "mental_health_admin" ON mental_health_responses FOR ALL
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'system_admin');

CREATE POLICY "mental_health_client_admin" ON mental_health_responses FOR SELECT
  USING (
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'client_admin'
    AND EXISTS (
      SELECT 1 FROM survey_responses sr
      WHERE sr.id = survey_response_id
        AND sr.client_code = (auth.jwt() -> 'app_metadata' ->> 'client_code')
    )
  );

CREATE POLICY "mental_health_anon_insert" ON mental_health_responses FOR INSERT
  WITH CHECK (auth.role() = 'anon');

-- company_support_responses
DROP POLICY IF EXISTS "company_support_admin"        ON company_support_responses;
DROP POLICY IF EXISTS "company_support_client_admin" ON company_support_responses;
DROP POLICY IF EXISTS "company_support_anon_insert"  ON company_support_responses;

CREATE POLICY "company_support_admin" ON company_support_responses FOR ALL
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'system_admin');

CREATE POLICY "company_support_client_admin" ON company_support_responses FOR SELECT
  USING (
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'client_admin'
    AND EXISTS (
      SELECT 1 FROM survey_responses sr
      WHERE sr.id = survey_response_id
        AND sr.client_code = (auth.jwt() -> 'app_metadata' ->> 'client_code')
    )
  );

CREATE POLICY "company_support_anon_insert" ON company_support_responses FOR INSERT
  WITH CHECK (auth.role() = 'anon');

-- work_life_responses
DROP POLICY IF EXISTS "work_life_admin"        ON work_life_responses;
DROP POLICY IF EXISTS "work_life_client_admin" ON work_life_responses;
DROP POLICY IF EXISTS "work_life_anon_insert"  ON work_life_responses;

CREATE POLICY "work_life_admin" ON work_life_responses FOR ALL
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'system_admin');

CREATE POLICY "work_life_client_admin" ON work_life_responses FOR SELECT
  USING (
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'client_admin'
    AND EXISTS (
      SELECT 1 FROM survey_responses sr
      WHERE sr.id = survey_response_id
        AND sr.client_code = (auth.jwt() -> 'app_metadata' ->> 'client_code')
    )
  );

CREATE POLICY "work_life_anon_insert" ON work_life_responses FOR INSERT
  WITH CHECK (auth.role() = 'anon');

-- exercise_responses
DROP POLICY IF EXISTS "exercise_admin"        ON exercise_responses;
DROP POLICY IF EXISTS "exercise_client_admin" ON exercise_responses;
DROP POLICY IF EXISTS "exercise_anon_insert"  ON exercise_responses;

CREATE POLICY "exercise_admin" ON exercise_responses FOR ALL
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'system_admin');

CREATE POLICY "exercise_client_admin" ON exercise_responses FOR SELECT
  USING (
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'client_admin'
    AND EXISTS (
      SELECT 1 FROM survey_responses sr
      WHERE sr.id = survey_response_id
        AND sr.client_code = (auth.jwt() -> 'app_metadata' ->> 'client_code')
    )
  );

CREATE POLICY "exercise_anon_insert" ON exercise_responses FOR INSERT
  WITH CHECK (auth.role() = 'anon');